// Generated by CoffeeScript 1.7.1
var div, input, label, renderable, _ref;

_ref = require('teacup'), renderable = _ref.renderable, div = _ref.div, input = _ref.input, label = _ref.label;

module.exports = {
  input: function(type) {
    return renderable(function(field) {
      var id, labelText, name, prefix;
      name = field.name, id = field.id, labelText = field.label, prefix = field.prefix;
      return div(function() {
        var attrs;
        label({
          "for": id
        }, labelText);
        attrs = {
          id: id,
          type: type
        };
        attrs["rv-" + prefix + "-value"] = "data." + name;
        return input('.form-control', attrs);
      });
    });
  }
};
